
name: "Security Analysis"

on:
  push:
    branches: [ main, protected ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '38 8 * * 1'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get upgrade
        sudo apt-get install mesa-common-dev clang libglfw3 libglfw3-dev
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      run: bazel shutdown; bazel build --config=debug --spawn_strategy=local --nouse_action_cache //...
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1